package akin.city_card.admin.model;

public enum ActionType {

    // 🔐 GİRİŞ / GÜVENLİK
    LOGIN,
    LOGOUT,
    RESET_PASSWORD,
    CHANGE_PASSWORD,
    VERIFICATION_SMS_SENT,
    PHONE_VERIFIED,
    EMAIL_VERIFIED,

    // 👤 KULLANICI HESABI
    SIGN_UP,
    COLLECTIVE_SIGN_UP,
    UPDATE_PROFILE,
    DELETE_USER,
    DEACTIVATE_ACCOUNT,
    ACTIVATE_ACCOUNT,
    UPLOAD_PROFILE_PHOTO,

    // 🛡️ YETKİLENDİRME / ADMIN
    APPROVE_ADMIN,
    BLOCK_USER,
    UNBLOCK_USER,
    PROMOTE_TO_ADMIN,
    DEMOTE_TO_USER,

    // 🚌 KART İŞLEMLERİ
    ADD_BUS_CARD,
    DELETE_BUS_CARD,
    UPDATE_BUS_CARD_ALIAS,
    FAVORITE_CARD_ADDED,
    FAVORITE_CARD_REMOVED,
    SET_LOW_BALANCE_ALERT,
    REMOVE_LOW_BALANCE_ALERT,
    BUS_CARD_TOP_UP,
    BUS_CARD_TRANSFER,

    // 🚏 ROTA VE GÜZERGAH
    FAVORITE_ROUTE_ADDED,
    FAVORITE_ROUTE_REMOVED,
    VIEW_ROUTE_DETAILS,

    // 🧭 KONUM / GEO
    LOCATION_UPDATED,
    ADD_GEO_ALERT,
    DELETE_GEO_ALERT,
    TRIGGERED_GEO_ALERT,

    // 👛 CÜZDAN VE ÖDEME
    CREATE_WALLET,
    DELETE_WALLET,
    WALLET_TOP_UP,
    AUTO_TOP_UP_ENABLED,
    AUTO_TOP_UP_DISABLED,
    AUTO_TOP_UP_CONFIG_ADDED,
    AUTO_TOP_UP_CONFIG_REMOVED,
    WALLET_TRANSFER,

    // 📢 BİLDİRİM VE TERCİHLER
    UPDATE_NOTIFICATION_PREFERENCES,
    NOTIFICATION_RECEIVED,
    NOTIFICATION_READ,

    // 📰 HABERLER
    VIEWED_NEWS,
    LIKED_NEWS,
    UNLIKED_NEWS,

    // 🔍 ARAMA VE GEÇMİŞ
    SEARCH_PERFORMED,
    SEARCH_HISTORY_CLEARED,

    // 🧪 DOĞRULAMA KODLARI
    SEND_PHONE_VERIFICATION_CODE,
    RESEND_PHONE_VERIFICATION_CODE,
    VERIFY_PHONE_CODE,

    // ⚙️ SİSTEM / GENEL
    SYSTEM_MAINTENANCE_START,
    SYSTEM_MAINTENANCE_END,
    SYSTEM_ALERT_ACKNOWLEDGED,

    // 📊 RAPOR VE ANALİZ
    EXPORT_USER_DATA,
    EXPORT_WALLET_HISTORY,
    EXPORT_LOGIN_HISTORY
}
